import type { User, Lesson, ProgressEntry, LearningInsight, TeachBackSubmission } from '@/types';

export const mockUsers: User[] = [
  {
    id: 's1',
    name: 'Maya',
    email: 'maya@nest.edu',
    role: 'student',
    avatar: '🦊',
    gradeLevel: 'Grade 3',
  },
  {
    id: 't1',
    name: 'Ms. Sarah',
    email: 'sarah@nest.edu',
    role: 'teacher',
    avatar: '👩‍🏫',
  },
  {
    id: 'p1',
    name: 'John (Maya\'s Dad)',
    email: 'john@nest.edu',
    role: 'parent',
    avatar: '👨',
    linkedStudents: ['s1'],
  },
  {
    id: 'th1',
    name: 'Dr. Emily',
    email: 'emily@nest.edu',
    role: 'therapist',
    avatar: '👩‍⚕️',
    linkedStudents: ['s1'],
  },
];

export const mockLessons: Lesson[] = [
  {
    id: 'l1',
    title: 'The Water Cycle Adventure',
    subject: 'Science',
    description: 'Learn how water moves around our planet through evaporation, condensation, and rain!',
    difficulty: 2,
    content: {
      story: 'Once upon a time, a tiny water droplet named Drippy lived in a big blue ocean. One sunny day, Drippy felt warm and light. He was evaporating! Up, up, up he went into the sky. High in the clouds, Drippy met lots of other droplets. They huddled together and formed a big fluffy cloud. This was condensation! Soon the cloud got too heavy. Drippy and his friends fell back down as rain. This is called precipitation. Drippy landed in a river that flowed back to the ocean. And so, Drippy\'s adventure began all over again!',
      pages: [
        { id: 'p1', text: 'Meet Drippy the water droplet! He lives in the big blue ocean with all his friends.', illustration: 'ocean', emoji: '💧' },
        { id: 'p2', text: 'One sunny day, Drippy felt warm and light. The sun made him float up, up, up into the sky! This is called EVAPORATION.', illustration: 'sun', emoji: '☀️' },
        { id: 'p3', text: 'High in the sky, Drippy met lots of other droplets. They hugged together to make a big fluffy cloud. This is called CONDENSATION.', illustration: 'cloud', emoji: '☁️' },
        { id: 'p4', text: 'Soon the cloud got too heavy! Drippy and his friends fell back down as rain. This is called PRECIPITATION.', illustration: 'rain', emoji: '🌧️' },
        { id: 'p5', text: 'Drippy landed in a river that carried him back to the ocean. And so, his adventure began all over again!', illustration: 'river', emoji: '🌊' },
      ],
      keyPoints: [
        'Evaporation: Water turns into vapor and goes up',
        'Condensation: Vapor forms clouds in the sky',
        'Precipitation: Water falls as rain or snow',
        'Collection: Water flows back to oceans and rivers',
      ],
      vocabulary: [
        { word: 'Evaporation', definition: 'When water gets warm and turns into vapor', emoji: '☀️' },
        { word: 'Condensation', definition: 'When water vapor cools and forms clouds', emoji: '☁️' },
        { word: 'Precipitation', definition: 'When water falls from clouds as rain', emoji: '🌧️' },
        { word: 'Water Cycle', definition: 'The journey of water moving around Earth', emoji: '🔄' },
      ],
    },
    activities: [
      {
        id: 'a1',
        type: 'quiz',
        title: 'Water Cycle Quiz',
        description: 'Test what you learned about the water cycle!',
        difficulty: 2,
        data: {
          questions: [
            { id: 'q1', question: 'What is it called when water turns into vapor and goes up?', emoji: '☀️', options: ['Condensation', 'Evaporation', 'Precipitation', 'Collection'], correctAnswer: 1, explanation: 'Evaporation is when the sun warms water and it turns into vapor, rising into the sky!' },
            { id: 'q2', question: 'What are clouds made of?', emoji: '☁️', options: ['Cotton candy', 'Water droplets', 'Smoke', 'Dust'], correctAnswer: 1, explanation: 'Clouds are made of tiny water droplets that huddled together in the sky!' },
            { id: 'q3', question: 'What is precipitation?', emoji: '🌧️', options: ['Water going up', 'Water forming clouds', 'Water falling as rain', 'Water in the ocean'], correctAnswer: 2, explanation: 'Precipitation is when water falls from clouds as rain, snow, or hail!' },
            { id: 'q4', question: 'Where does the water cycle start?', emoji: '🔄', options: ['In the sky', 'In the ocean', 'In the clouds', 'In the river'], correctAnswer: 1, explanation: 'The water cycle starts in the ocean, where the sun warms the water!' },
          ],
        },
      },
      {
        id: 'a2',
        type: 'flashcards',
        title: 'Water Words Flashcards',
        description: 'Learn important water cycle words!',
        difficulty: 1,
        data: {
          flashcards: [
            { front: 'Evaporation', back: 'Water turning into vapor from heat', emoji: '☀️' },
            { front: 'Condensation', back: 'Water vapor forming clouds', emoji: '☁️' },
            { front: 'Precipitation', back: 'Water falling as rain', emoji: '🌧️' },
            { front: 'Collection', back: 'Water flowing back to oceans', emoji: '🌊' },
            { front: 'Water Vapor', back: 'Water in gas form in the air', emoji: '💨' },
            { front: 'Droplet', back: 'A tiny drop of water', emoji: '💧' },
          ],
        },
      },
      {
        id: 'a3',
        type: 'memory-game',
        title: 'Water Cycle Memory Match',
        description: 'Match the water cycle pictures!',
        difficulty: 2,
        data: {
          cards: [
            { id: 'c1', emoji: '☀️', label: 'Sun' },
            { id: 'c2', emoji: '☁️', label: 'Cloud' },
            { id: 'c3', emoji: '🌧️', label: 'Rain' },
            { id: 'c4', emoji: '🌊', label: 'Ocean' },
            { id: 'c5', emoji: '💧', label: 'Droplet' },
            { id: 'c6', emoji: '💨', label: 'Vapor' },
          ],
        },
      },
      {
        id: 'a4',
        type: 'word-recognition',
        title: 'Water Cycle Words',
        description: 'Find the correct water cycle words!',
        difficulty: 2,
        data: {
          words: [
            { word: 'Evaporation', correct: true, emoji: '☀️' },
            { word: 'Evapration', correct: false, emoji: '❌' },
            { word: 'Condensation', correct: true, emoji: '☁️' },
            { word: 'Condensashun', correct: false, emoji: '❌' },
            { word: 'Precipitation', correct: true, emoji: '🌧️' },
            { word: 'Preciptation', correct: false, emoji: '❌' },
            { word: 'Collection', correct: true, emoji: '🌊' },
            { word: 'Collecshun', correct: false, emoji: '❌' },
          ],
        },
      },
    ],
    status: 'in-progress',
    progress: 45,
    assignedTo: ['s1'],
    createdAt: '2026-09-10',
    createdBy: 't1',
    thumbnail: '💧',
    estimatedTime: 20,
  },
  {
    id: 'l2',
    title: 'Numbers Are Friends',
    subject: 'Math',
    description: 'Discover how numbers work together through fun stories and games!',
    difficulty: 1,
    content: {
      story: 'In a magical number land, there lived Number 5. Number 5 was sad because he thought he was all alone. But then he met Number 3. "Let\'s add together!" said Number 3. 5 + 3 = 8! Number 5 was so happy to find that when numbers add together, they make bigger numbers. Then they met Number 2. "Let\'s subtract!" said Number 2. 5 - 2 = 3. Numbers can add to grow and subtract to shrink. They are all friends!',
      pages: [
        { id: 'p1', text: 'In a magical number land, there lived Number 5. He felt a bit lonely.', illustration: 'number', emoji: '5️⃣' },
        { id: 'p2', text: 'Then Number 3 came along! "Let\'s ADD together!" said Number 3. 5 + 3 = 8!', illustration: 'plus', emoji: '➕' },
        { id: 'p3', text: 'Number 5 was so happy! Adding made them bigger and stronger together.', illustration: 'happy', emoji: '😊' },
        { id: 'p4', text: 'Then they met Number 2. "Let\'s SUBTRACT!" said Number 2. 5 - 2 = 3.', illustration: 'minus', emoji: '➖' },
        { id: 'p5', text: 'Numbers can add to grow and subtract to shrink. They are all friends in Number Land!', illustration: 'friends', emoji: '🔢' },
      ],
      keyPoints: [
        'Addition: Combining numbers to make a bigger number',
        'Subtraction: Taking away to make a smaller number',
        'Plus (+) means add, Minus (-) means take away',
        'Numbers are friends that work together',
      ],
      vocabulary: [
        { word: 'Addition', definition: 'Putting numbers together', emoji: '➕' },
        { word: 'Subtraction', definition: 'Taking numbers away', emoji: '➖' },
        { word: 'Plus', definition: 'The symbol for adding (+)', emoji: '➕' },
        { word: 'Minus', definition: 'The symbol for subtracting (-)', emoji: '➖' },
      ],
    },
    activities: [
      {
        id: 'a5',
        type: 'quiz',
        title: 'Number Friends Quiz',
        description: 'Test your addition and subtraction!',
        difficulty: 1,
        data: {
          questions: [
            { id: 'q1', question: 'What is 5 + 3?', emoji: '➕', options: ['7', '8', '9', '10'], correctAnswer: 1, explanation: 'When you add 5 and 3, you get 8!' },
            { id: 'q2', question: 'What is 5 - 2?', emoji: '➖', options: ['2', '3', '4', '5'], correctAnswer: 1, explanation: 'When you subtract 2 from 5, you get 3!' },
            { id: 'q3', question: 'What does the + symbol mean?', emoji: '➕', options: ['Subtract', 'Add', 'Multiply', 'Divide'], correctAnswer: 1, explanation: 'The + symbol means ADD - putting numbers together!' },
            { id: 'q4', question: 'What does the - symbol mean?', emoji: '➖', options: ['Add', 'Subtract', 'Multiply', 'Divide'], correctAnswer: 1, explanation: 'The - symbol means SUBTRACT - taking numbers away!' },
          ],
        },
      },
      {
        id: 'a6',
        type: 'flashcards',
        title: 'Math Words Flashcards',
        description: 'Learn math words!',
        difficulty: 1,
        data: {
          flashcards: [
            { front: 'Addition', back: 'Putting numbers together', emoji: '➕' },
            { front: 'Subtraction', back: 'Taking numbers away', emoji: '➖' },
            { front: 'Plus (+)', back: 'The symbol for adding', emoji: '➕' },
            { front: 'Minus (-)', back: 'The symbol for subtracting', emoji: '➖' },
            { front: 'Sum', back: 'The answer to an addition', emoji: '🟰' },
            { front: 'Difference', back: 'The answer to a subtraction', emoji: '🟰' },
          ],
        },
      },
      {
        id: 'a7',
        type: 'picture-matching',
        title: 'Match the Math Symbols',
        description: 'Match symbols with their meanings!',
        difficulty: 1,
        data: {
          pairs: [
            { left: { id: 'l1', emoji: '➕', label: 'Plus' }, right: { id: 'r1', emoji: '🤝', label: 'Add together' } },
            { left: { id: 'l2', emoji: '➖', label: 'Minus' }, right: { id: 'r2', emoji: '👋', label: 'Take away' } },
            { left: { id: 'l3', emoji: '🟰', label: 'Equals' }, right: { id: 'r3', emoji: '⚖️', label: 'Same as' } },
            { left: { id: 'l4', emoji: '5️⃣', label: 'Five' }, right: { id: 'r4', emoji: '🖐️', label: '5 fingers' } },
          ],
        },
      },
    ],
    status: 'completed',
    progress: 100,
    assignedTo: ['s1'],
    createdAt: '2026-09-05',
    createdBy: 't1',
    thumbnail: '🔢',
    estimatedTime: 15,
  },
  {
    id: 'l3',
    title: 'The Kindness Garden',
    subject: 'Social Studies',
    description: 'Learn about kindness, sharing, and being a good friend through a beautiful story!',
    difficulty: 1,
    content: {
      story: 'In a small village, there was a garden that nobody visited. It was full of weeds and looked sad. A little girl named Lily decided to change that. Every day, she pulled out one weed and planted one flower. Soon, her friend Tom came to help. Then, more children joined. They all worked together, sharing their seeds and water. The garden became the most beautiful place in the village. Everyone was happy because they had built it together with kindness and sharing!',
      pages: [
        { id: 'p1', text: 'In a small village, there was a garden that nobody visited. It was full of weeds.', illustration: 'sad-garden', emoji: '🥀' },
        { id: 'p2', text: 'A little girl named Lily decided to help. Every day, she pulled out one weed and planted one flower.', illustration: 'girl', emoji: '👧' },
        { id: 'p3', text: 'Her friend Tom came to help. "Let\'s share the work!" he said.', illustration: 'friends', emoji: '🤝' },
        { id: 'p4', text: 'More children joined. They shared their seeds and water with each other.', illustration: 'sharing', emoji: '🌱' },
        { id: 'p5', text: 'The garden became the most beautiful place in the village! Everyone was happy because they built it together with kindness!', illustration: 'beautiful-garden', emoji: '🌸' },
      ],
      keyPoints: [
        'Kindness makes the world better',
        'Sharing helps everyone',
        'Working together is powerful',
        'Small acts of kindness grow into big changes',
      ],
      vocabulary: [
        { word: 'Kindness', definition: 'Being nice and helpful to others', emoji: '💗' },
        { word: 'Sharing', definition: 'Giving some of what you have to others', emoji: '🤝' },
        { word: 'Together', definition: 'Doing something with other people', emoji: '👥' },
        { word: 'Community', definition: 'A group of people who help each other', emoji: '🏘️' },
      ],
    },
    activities: [
      {
        id: 'a8',
        type: 'quiz',
        title: 'Kindness Quiz',
        description: 'Test what you learned about kindness!',
        difficulty: 1,
        data: {
          questions: [
            { id: 'q1', question: 'What did Lily do to help the garden?', emoji: '👧', options: ['Nothing', 'Pulled weeds and planted flowers', 'Played games', 'Went home'], correctAnswer: 1, explanation: 'Lily pulled out weeds and planted flowers every day to help the garden!' },
            { id: 'q2', question: 'How did the children share?', emoji: '🤝', options: ['They didn\'t share', 'They shared seeds and water', 'They fought', 'They ran away'], correctAnswer: 1, explanation: 'The children shared their seeds and water with each other!' },
            { id: 'q3', question: 'What happened when everyone worked together?', emoji: '🌸', options: ['Nothing changed', 'The garden became beautiful', 'The garden got worse', 'They got tired'], correctAnswer: 1, explanation: 'When everyone worked together with kindness, the garden became beautiful!' },
            { id: 'q4', question: 'What is kindness?', emoji: '💗', options: ['Being mean', 'Being nice and helpful', 'Being quiet', 'Being fast'], correctAnswer: 1, explanation: 'Kindness means being nice and helpful to others!' },
          ],
        },
      },
      {
        id: 'a9',
        type: 'memory-game',
        title: 'Kindness Memory Match',
        description: 'Match the kindness pictures!',
        difficulty: 1,
        data: {
          cards: [
            { id: 'c1', emoji: '🌸', label: 'Flower' },
            { id: 'c2', emoji: '🤝', label: 'Sharing' },
            { id: 'c3', emoji: '💗', label: 'Kindness' },
            { id: 'c4', emoji: '🌱', label: 'Seed' },
            { id: 'c5', emoji: '👧', label: 'Lily' },
            { id: 'c6', emoji: '🧒', label: 'Tom' },
          ],
        },
      },
      {
        id: 'a10',
        type: 'word-recognition',
        title: 'Kindness Words',
        description: 'Find the correct kindness words!',
        difficulty: 1,
        data: {
          words: [
            { word: 'Kindness', correct: true, emoji: '💗' },
            { word: 'Kindnes', correct: false, emoji: '❌' },
            { word: 'Sharing', correct: true, emoji: '🤝' },
            { word: 'Sharen', correct: false, emoji: '❌' },
            { word: 'Together', correct: true, emoji: '👥' },
            { word: 'Togther', correct: false, emoji: '❌' },
            { word: 'Community', correct: true, emoji: '🏘️' },
            { word: 'Comunity', correct: false, emoji: '❌' },
          ],
        },
      },
    ],
    status: 'not-started',
    progress: 0,
    assignedTo: ['s1'],
    createdAt: '2026-09-12',
    createdBy: 't1',
    thumbnail: '🌸',
    estimatedTime: 15,
  },
  {
    id: 'l4',
    title: 'Animal Habitats: Where Do They Live?',
    subject: 'Science',
    description: 'Explore where different animals live and why their homes are perfect for them!',
    difficulty: 3,
    content: {
      story: 'Let\'s go on an adventure to visit animal homes! First, we visit the Arctic, where polar bears live. They have thick fur to stay warm in the snow. Next, we travel to the rainforest, where colorful parrots live high in the trees. Then we visit the ocean, where dolphins swim and play. In the desert, camels store water in their humps. And in the forest, squirrels build cozy nests in trees. Every animal has a special home that is perfect for them!',
      pages: [
        { id: 'p1', text: 'Let\'s visit animal homes! First, the Arctic. Polar bears live here with their thick warm fur.', illustration: 'arctic', emoji: '🐻‍❄️' },
        { id: 'p2', text: 'Next, the rainforest! Colorful parrots live high in the tall green trees.', illustration: 'rainforest', emoji: '🦜' },
        { id: 'p3', text: 'Then, the ocean! Dolphins swim and play in the deep blue water.', illustration: 'ocean', emoji: '🐬' },
        { id: 'p4', text: 'In the desert, camels store water in their humps to survive the hot, dry days.', illustration: 'desert', emoji: '🐫' },
        { id: 'p5', text: 'And in the forest, squirrels build cozy nests in the trees. Every animal has a perfect home!', illustration: 'forest', emoji: '🐿️' },
      ],
      keyPoints: [
        'Animals live in habitats that suit their needs',
        'Polar bears have thick fur for cold Arctic',
        'Parrots live in rainforest trees',
        'Dolphins live in the ocean',
        'Camels store water for desert survival',
      ],
      vocabulary: [
        { word: 'Habitat', definition: 'The natural home of an animal', emoji: '🏠' },
        { word: 'Arctic', definition: 'A very cold, snowy place near the North Pole', emoji: '❄️' },
        { word: 'Rainforest', definition: 'A warm, wet forest with lots of rain', emoji: '🌳' },
        { word: 'Desert', definition: 'A hot, dry place with little water', emoji: '🏜️' },
      ],
    },
    activities: [
      {
        id: 'a11',
        type: 'quiz',
        title: 'Animal Homes Quiz',
        description: 'Match animals to their habitats!',
        difficulty: 3,
        data: {
          questions: [
            { id: 'q1', question: 'Where do polar bears live?', emoji: '🐻‍❄️', options: ['Desert', 'Rainforest', 'Arctic', 'Ocean'], correctAnswer: 2, explanation: 'Polar bears live in the Arctic where it is cold and snowy!' },
            { id: 'q2', question: 'Why do camels have humps?', emoji: '🐫', options: ['To look tall', 'To store water', 'To sleep', 'To jump'], correctAnswer: 1, explanation: 'Camels store water in their humps to survive in the hot desert!' },
            { id: 'q3', question: 'Where do parrots live?', emoji: '🦜', options: ['Arctic', 'Desert', 'Rainforest', 'Ocean'], correctAnswer: 2, explanation: 'Parrots live high in the trees of the rainforest!' },
            { id: 'q4', question: 'What is a habitat?', emoji: '🏠', options: ['An animal\'s food', 'An animal\'s home', 'An animal\'s name', 'An animal\'s color'], correctAnswer: 1, explanation: 'A habitat is the natural home where an animal lives!' },
          ],
        },
      },
      {
        id: 'a12',
        type: 'picture-matching',
        title: 'Match Animals to Homes',
        description: 'Match each animal to its habitat!',
        difficulty: 3,
        data: {
          pairs: [
            { left: { id: 'l1', emoji: '🐻‍❄️', label: 'Polar Bear' }, right: { id: 'r1', emoji: '❄️', label: 'Arctic' } },
            { left: { id: 'l2', emoji: '🦜', label: 'Parrot' }, right: { id: 'r2', emoji: '🌳', label: 'Rainforest' } },
            { left: { id: 'l3', emoji: '🐬', label: 'Dolphin' }, right: { id: 'r3', emoji: '🌊', label: 'Ocean' } },
            { left: { id: 'l4', emoji: '🐫', label: 'Camel' }, right: { id: 'r4', emoji: '🏜️', label: 'Desert' } },
          ],
        },
      },
      {
        id: 'a13',
        type: 'flashcards',
        title: 'Habitat Words',
        description: 'Learn habitat vocabulary!',
        difficulty: 3,
        data: {
          flashcards: [
            { front: 'Habitat', back: 'The natural home of an animal', emoji: '🏠' },
            { front: 'Arctic', back: 'Cold, snowy place near North Pole', emoji: '❄️' },
            { front: 'Rainforest', back: 'Warm, wet forest with lots of rain', emoji: '🌳' },
            { front: 'Desert', back: 'Hot, dry place with little water', emoji: '🏜️' },
            { front: 'Ocean', back: 'Large body of salt water', emoji: '🌊' },
            { front: 'Forest', back: 'Area covered with trees', emoji: '🌲' },
          ],
        },
      },
    ],
    status: 'in-progress',
    progress: 20,
    assignedTo: ['s1'],
    createdAt: '2026-09-13',
    createdBy: 't1',
    thumbnail: '🐻‍❄️',
    estimatedTime: 25,
  },
  {
    id: 'l5',
    title: 'The Magic of Colors',
    subject: 'Art',
    description: 'Discover how colors mix to make new colors through a magical story!',
    difficulty: 1,
    content: {
      story: 'In a magical paint box, there lived three friends: Red, Blue, and Yellow. One day, Red and Blue bumped into each other. "Oh no!" they cried. But when they looked, they had made Purple! It was magic! Then Blue and Yellow mixed together and made Green. Red and Yellow mixed to make Orange. The three friends were so excited. They could make so many new colors just by mixing together. From that day on, they called themselves the Color Family!',
      pages: [
        { id: 'p1', text: 'In a magical paint box lived three friends: Red, Blue, and Yellow.', illustration: 'paintbox', emoji: '🎨' },
        { id: 'p2', text: 'One day, Red and Blue bumped into each other and made Purple! It was magic!', illustration: 'mixing', emoji: '🟣' },
        { id: 'p3', text: 'Blue and Yellow mixed together and made Green!', illustration: 'green', emoji: '🟢' },
        { id: 'p4', text: 'Red and Yellow mixed to make Orange!', illustration: 'orange', emoji: '🟠' },
        { id: 'p5', text: 'The three friends were so excited. They called themselves the Color Family!', illustration: 'colors', emoji: '🌈' },
      ],
      keyPoints: [
        'Red + Blue = Purple',
        'Blue + Yellow = Green',
        'Red + Yellow = Orange',
        'Mixing colors makes new colors',
      ],
      vocabulary: [
        { word: 'Primary Colors', definition: 'Red, Blue, and Yellow - the main colors', emoji: '🔴' },
        { word: 'Secondary Colors', definition: 'Colors made by mixing primary colors', emoji: '🟣' },
        { word: 'Mix', definition: 'To combine two or more things', emoji: '🎨' },
        { word: 'Purple', definition: 'The color made by mixing red and blue', emoji: '🟣' },
      ],
    },
    activities: [
      {
        id: 'a14',
        type: 'quiz',
        title: 'Color Magic Quiz',
        description: 'Test your color mixing!',
        difficulty: 1,
        data: {
          questions: [
            { id: 'q1', question: 'What color do you get from Red + Blue?', emoji: '🎨', options: ['Green', 'Orange', 'Purple', 'Yellow'], correctAnswer: 2, explanation: 'Red and Blue mix to make Purple!' },
            { id: 'q2', question: 'What color do you get from Blue + Yellow?', emoji: '🎨', options: ['Green', 'Orange', 'Purple', 'Red'], correctAnswer: 0, explanation: 'Blue and Yellow mix to make Green!' },
            { id: 'q3', question: 'What are the primary colors?', emoji: '🔴', options: ['Green, Orange, Purple', 'Red, Blue, Yellow', 'Pink, Brown, Gray', 'Black, White, Gold'], correctAnswer: 1, explanation: 'The primary colors are Red, Blue, and Yellow!' },
            { id: 'q4', question: 'What color do you get from Red + Yellow?', emoji: '🟠', options: ['Green', 'Orange', 'Purple', 'Blue'], correctAnswer: 1, explanation: 'Red and Yellow mix to make Orange!' },
          ],
        },
      },
      {
        id: 'a15',
        type: 'memory-game',
        title: 'Color Memory Match',
        description: 'Match the color pictures!',
        difficulty: 1,
        data: {
          cards: [
            { id: 'c1', emoji: '🔴', label: 'Red' },
            { id: 'c2', emoji: '🔵', label: 'Blue' },
            { id: 'c3', emoji: '🟡', label: 'Yellow' },
            { id: 'c4', emoji: '🟣', label: 'Purple' },
            { id: 'c5', emoji: '🟢', label: 'Green' },
            { id: 'c6', emoji: '🟠', label: 'Orange' },
          ],
        },
      },
    ],
    status: 'completed',
    progress: 100,
    assignedTo: ['s1'],
    createdAt: '2026-09-08',
    createdBy: 't1',
    thumbnail: '🎨',
    estimatedTime: 15,
  },
  {
    id: 'l6',
    title: 'Our Solar System Journey',
    subject: 'Science',
    description: 'Travel through space and visit all the planets in our solar system!',
    difficulty: 4,
    content: {
      story: 'Blast off! We\'re going on a journey through our solar system. First, we visit the Sun, the big star at the center. It\'s so hot and bright! Next, we fly to Mercury, the smallest planet. Then Venus, the hottest planet. Earth is our beautiful blue home. Mars is the red planet. Jupiter is the biggest planet with a giant red spot. Saturn has beautiful rings. Uranus spins on its side. And Neptune is the windiest planet. Each planet is unique and amazing!',
      pages: [
        { id: 'p1', text: 'Blast off! We start at the Sun, the big hot star at the center of our solar system.', illustration: 'sun', emoji: '☀️' },
        { id: 'p2', text: 'Next, Mercury - the smallest planet, closest to the Sun.', illustration: 'mercury', emoji: '☿️' },
        { id: 'p3', text: 'Earth is our beautiful blue home with water and life!', illustration: 'earth', emoji: '🌍' },
        { id: 'p4', text: 'Mars is the red planet. Jupiter is the biggest with a giant red spot!', illustration: 'planets', emoji: '🪐' },
        { id: 'p5', text: 'Saturn has beautiful rings. Each planet is unique and amazing!', illustration: 'saturn', emoji: '🪐' },
      ],
      keyPoints: [
        'The Sun is at the center of our solar system',
        'Mercury is the smallest planet',
        'Earth is our home with water and life',
        'Jupiter is the largest planet',
        'Saturn has beautiful rings',
      ],
      vocabulary: [
        { word: 'Solar System', definition: 'The Sun and all the planets that orbit it', emoji: '☀️' },
        { word: 'Planet', definition: 'A large round object that orbits a star', emoji: '🪐' },
        { word: 'Orbit', definition: 'The path a planet takes around the Sun', emoji: '🔄' },
        { word: 'Sun', definition: 'The big hot star at the center of our system', emoji: '☀️' },
      ],
    },
    activities: [
      {
        id: 'a16',
        type: 'quiz',
        title: 'Solar System Quiz',
        description: 'Test your space knowledge!',
        difficulty: 4,
        data: {
          questions: [
            { id: 'q1', question: 'What is at the center of our solar system?', emoji: '☀️', options: ['Earth', 'The Moon', 'The Sun', 'Mars'], correctAnswer: 2, explanation: 'The Sun is the big hot star at the center of our solar system!' },
            { id: 'q2', question: 'Which is the smallest planet?', emoji: '☿️', options: ['Earth', 'Mercury', 'Mars', 'Jupiter'], correctAnswer: 1, explanation: 'Mercury is the smallest planet, closest to the Sun!' },
            { id: 'q3', question: 'Which planet is our home?', emoji: '🌍', options: ['Mars', 'Venus', 'Earth', 'Jupiter'], correctAnswer: 2, explanation: 'Earth is our beautiful blue home with water and life!' },
            { id: 'q4', question: 'Which planet has beautiful rings?', emoji: '🪐', options: ['Mars', 'Saturn', 'Earth', 'Mercury'], correctAnswer: 1, explanation: 'Saturn has beautiful rings made of ice and rock!' },
          ],
        },
      },
      {
        id: 'a17',
        type: 'picture-matching',
        title: 'Match the Planets',
        description: 'Match planets to their descriptions!',
        difficulty: 4,
        data: {
          pairs: [
            { left: { id: 'l1', emoji: '☀️', label: 'Sun' }, right: { id: 'r1', emoji: '🔥', label: 'Hot star' } },
            { left: { id: 'l2', emoji: '🌍', label: 'Earth' }, right: { id: 'r2', emoji: '💧', label: 'Blue home' } },
            { left: { id: 'l3', emoji: '🪐', label: 'Saturn' }, right: { id: 'r3', emoji: '💍', label: 'Has rings' } },
            { left: { id: 'l4', emoji: '☿️', label: 'Mercury' }, right: { id: 'r4', emoji: '📏', label: 'Smallest' } },
          ],
        },
      },
      {
        id: 'a18',
        type: 'flashcards',
        title: 'Space Words Flashcards',
        description: 'Learn space vocabulary!',
        difficulty: 4,
        data: {
          flashcards: [
            { front: 'Solar System', back: 'The Sun and all planets orbiting it', emoji: '☀️' },
            { front: 'Planet', back: 'A round object orbiting a star', emoji: '🪐' },
            { front: 'Orbit', back: 'The path around the Sun', emoji: '🔄' },
            { front: 'Sun', back: 'The star at the center', emoji: '☀️' },
            { front: 'Earth', back: 'Our home planet', emoji: '🌍' },
            { front: 'Saturn', back: 'The planet with rings', emoji: '🪐' },
          ],
        },
      },
    ],
    status: 'not-started',
    progress: 0,
    assignedTo: ['s1'],
    createdAt: '2026-09-14',
    createdBy: 't1',
    thumbnail: '🪐',
    estimatedTime: 30,
  },
];

export const mockProgress: ProgressEntry[] = [
  { id: 'pr1', studentId: 's1', lessonId: 'l2', lessonTitle: 'Numbers Are Friends', subject: 'Math', score: 90, timeSpent: 12, date: '2026-09-06', activitiesCompleted: 3, totalActivities: 3, difficulty: 1 },
  { id: 'pr2', studentId: 's1', lessonId: 'l5', lessonTitle: 'The Magic of Colors', subject: 'Art', score: 95, timeSpent: 10, date: '2026-09-09', activitiesCompleted: 2, totalActivities: 2, difficulty: 1 },
  { id: 'pr3', studentId: 's1', lessonId: 'l1', lessonTitle: 'The Water Cycle Adventure', subject: 'Science', score: 75, timeSpent: 8, date: '2026-09-11', activitiesCompleted: 2, totalActivities: 4, difficulty: 2 },
  { id: 'pr4', studentId: 's1', lessonId: 'l4', lessonTitle: 'Animal Habitats', subject: 'Science', score: 60, timeSpent: 5, date: '2026-09-13', activitiesCompleted: 1, totalActivities: 3, difficulty: 3 },
];

export const mockInsights: LearningInsight[] = [
  { id: 'i1', studentId: 's1', type: 'strength', category: 'Math', title: 'Strong in Addition', description: 'Maya shows excellent understanding of basic addition and subtraction concepts.', value: 90, trend: 'up' },
  { id: 'i2', studentId: 's1', type: 'strength', category: 'Art', title: 'Creative Thinking', description: 'Maya excels in creative and visual learning activities.', value: 95, trend: 'up' },
  { id: 'i3', studentId: 's1', type: 'needs-practice', category: 'Science', title: 'Science Vocabulary', description: 'Maya may benefit from more practice with science-specific vocabulary words.', value: 60, trend: 'stable' },
  { id: 'i4', studentId: 's1', type: 'needs-practice', category: 'Reading', title: 'Word Recognition', description: 'Maya sometimes confuses similar-looking words. Flashcard practice recommended.', value: 65, trend: 'down' },
  { id: 'i5', studentId: 's1', type: 'recommendation', category: 'Science', title: 'Try the Solar System lesson', description: 'Based on Maya\'s interest in the Water Cycle, she might enjoy learning about space!', value: 80, trend: 'up' },
  { id: 'i6', studentId: 's1', type: 'engagement', category: 'Overall', title: 'Engagement Level', description: 'Maya is most engaged with story-based and visual learning. Audio narration increases focus by 40%.', value: 85, trend: 'up' },
  { id: 'i7', studentId: 's1', type: 'engagement', category: 'Activities', title: 'Activity Preference', description: 'Maya completes 95% of memory games and quizzes, but only 60% of word recognition activities.', value: 75, trend: 'stable' },
  { id: 'i8', studentId: 's1', type: 'recommendation', category: 'Accessibility', title: 'Audio Learning', description: 'Maya responds well to audio narration. Consider enabling text-to-speech for all lessons.', value: 85, trend: 'up' },
];

export const mockTeachBacks: TeachBackSubmission[] = [
  {
    id: 'tb1',
    studentId: 's1',
    lessonId: 'l2',
    lessonTitle: 'Numbers Are Friends',
    mode: 'text',
    content: 'I learned that when you add numbers together they get bigger like 5 plus 3 is 8. And when you subtract they get smaller like 5 minus 2 is 3. The plus sign means add and the minus sign means take away.',
    aiEvaluation: {
      understandingScore: 92,
      strengths: ['Correctly explains addition', 'Correctly explains subtraction', 'Identifies math symbols correctly'],
      weakAreas: ['Could practice more complex addition problems'],
      feedback: 'Excellent work, Maya! You understand addition and subtraction really well. Try adding bigger numbers next time!',
    },
    date: '2026-09-06',
  },
  {
    id: 'tb2',
    studentId: 's1',
    lessonId: 'l5',
    lessonTitle: 'The Magic of Colors',
    mode: 'voice',
    content: 'I learned that red and blue make purple. And blue and yellow make green. And red and yellow make orange. The three main colors are red blue and yellow.',
    aiEvaluation: {
      understandingScore: 95,
      strengths: ['Correctly identifies all color combinations', 'Names all primary colors', 'Clear explanation'],
      weakAreas: [],
      feedback: 'Amazing job, Maya! You remembered all the color combinations perfectly. You are a color expert!',
    },
    date: '2026-09-09',
  },
];

export const subjectColors: Record<string, { bg: string; text: string; border: string; emoji: string }> = {
  Science: { bg: 'bg-nest-blue-100', text: 'text-nest-blue-700', border: 'border-nest-blue-300', emoji: '🔬' },
  Math: { bg: 'bg-nest-green-100', text: 'text-nest-green-700', border: 'border-nest-green-300', emoji: '🔢' },
  'Social Studies': { bg: 'bg-nest-peach-100', text: 'text-nest-peach-700', border: 'border-nest-peach-300', emoji: '🌍' },
  Art: { bg: 'bg-nest-yellow-100', text: 'text-nest-yellow-700', border: 'border-nest-yellow-300', emoji: '🎨' },
  English: { bg: 'bg-nest-lavender-100', text: 'text-nest-lavender-700', border: 'border-nest-lavender-300', emoji: '📖' },
};

export const difficultyLabels: Record<number, { label: string; color: string }> = {
  1: { label: 'Very Easy', color: 'bg-nest-green-200 text-nest-green-700' },
  2: { label: 'Easy', color: 'bg-nest-blue-200 text-nest-blue-700' },
  3: { label: 'Medium', color: 'bg-nest-yellow-200 text-nest-yellow-700' },
  4: { label: 'Challenging', color: 'bg-nest-peach-200 text-nest-peach-700' },
  5: { label: 'Advanced', color: 'bg-nest-lavender-200 text-nest-lavender-700' },
};
